// Generated by gencpp from file tiggo_msgs/RealCurb.msg
// DO NOT EDIT!


#ifndef TIGGO_MSGS_MESSAGE_REALCURB_H
#define TIGGO_MSGS_MESSAGE_REALCURB_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace tiggo_msgs
{
template <class ContainerAllocator>
struct RealCurb_
{
  typedef RealCurb_<ContainerAllocator> Type;

  RealCurb_()
    : header()
    , vaild(0)
    , top_x(0.0)
    , top_y(0.0)
    , down_x(0.0)
    , down_y(0.0)  {
    }
  RealCurb_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , vaild(0)
    , top_x(0.0)
    , top_y(0.0)
    , down_x(0.0)
    , down_y(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int8_t _vaild_type;
  _vaild_type vaild;

   typedef double _top_x_type;
  _top_x_type top_x;

   typedef double _top_y_type;
  _top_y_type top_y;

   typedef double _down_x_type;
  _down_x_type down_x;

   typedef double _down_y_type;
  _down_y_type down_y;




  typedef boost::shared_ptr< ::tiggo_msgs::RealCurb_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tiggo_msgs::RealCurb_<ContainerAllocator> const> ConstPtr;

}; // struct RealCurb_

typedef ::tiggo_msgs::RealCurb_<std::allocator<void> > RealCurb;

typedef boost::shared_ptr< ::tiggo_msgs::RealCurb > RealCurbPtr;
typedef boost::shared_ptr< ::tiggo_msgs::RealCurb const> RealCurbConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tiggo_msgs::RealCurb_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tiggo_msgs::RealCurb_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace tiggo_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'tiggo_msgs': ['/home/cyberc3/SSD-Tensorflow-master/pedestrian_ws/src/tiggo_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::tiggo_msgs::RealCurb_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tiggo_msgs::RealCurb_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tiggo_msgs::RealCurb_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tiggo_msgs::RealCurb_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tiggo_msgs::RealCurb_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tiggo_msgs::RealCurb_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tiggo_msgs::RealCurb_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1acd2fbcf7af010c53a254cf0ccd9e7b";
  }

  static const char* value(const ::tiggo_msgs::RealCurb_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1acd2fbcf7af010cULL;
  static const uint64_t static_value2 = 0x53a254cf0ccd9e7bULL;
};

template<class ContainerAllocator>
struct DataType< ::tiggo_msgs::RealCurb_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tiggo_msgs/RealCurb";
  }

  static const char* value(const ::tiggo_msgs::RealCurb_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tiggo_msgs::RealCurb_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
#std_msgs/Header header\n\
int8 vaild\n\
float64 top_x\n\
float64 top_y\n\
float64 down_x\n\
float64 down_y\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::tiggo_msgs::RealCurb_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tiggo_msgs::RealCurb_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.vaild);
      stream.next(m.top_x);
      stream.next(m.top_y);
      stream.next(m.down_x);
      stream.next(m.down_y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RealCurb_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tiggo_msgs::RealCurb_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tiggo_msgs::RealCurb_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "vaild: ";
    Printer<int8_t>::stream(s, indent + "  ", v.vaild);
    s << indent << "top_x: ";
    Printer<double>::stream(s, indent + "  ", v.top_x);
    s << indent << "top_y: ";
    Printer<double>::stream(s, indent + "  ", v.top_y);
    s << indent << "down_x: ";
    Printer<double>::stream(s, indent + "  ", v.down_x);
    s << indent << "down_y: ";
    Printer<double>::stream(s, indent + "  ", v.down_y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TIGGO_MSGS_MESSAGE_REALCURB_H
