(cl:in-package tiggo_msgs-msg)
(cl:export '(ID-VAL
          ID
          LONGITUDE-VAL
          LONGITUDE
          LATITUDE-VAL
          LATITUDE
          ATTRIBUTE1-VAL
          ATTRIBUTE1
          ATTRIBUTE2-VAL
          ATTRIBUTE2
          ONETWOWAY-VAL
          ONETWOWAY
          WAYSUM-VAL
          WAYSUM
          TARGETWAY-VAL
          TARGETWAY
          LANEWIDTH-VAL
          LANEWIDTH
          D2LCURB-VAL
          D2LCURB
          D2RCURB-VAL
          D2RCURB
          TARGET_DIST-VAL
          TARGET_DIST
          TOTALS-VAL
          TOTALS
          STOP-VAL
          STOP
          PEDESTRIAN-VAL
          PEDESTRIAN
))